-- 코드를 입력하세요
SELECT p.PRODUCT_ID,	PRODUCT_NAME, sum(PRICE*AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT p join FOOD_ORDER o on p.PRODUCT_ID=o.PRODUCT_ID
where YEAR(PRODUCE_DATE)=2022 and MONTH(PRODUCE_DATE)=05
group by p.PRODUCT_ID	
order by TOTAL_SALES desc, p.PRODUCT_ID