-- 코드를 입력하세요
SELECT u.USER_ID,	u.NICKNAME,	sum(PRICE) as TOTAL_SALES
from USED_GOODS_USER u join USED_GOODS_BOARD b on b.WRITER_ID=u.USER_ID
where STATUS='DONE'
group by b.WRITER_ID
having sum(PRICE)>=700000
order by TOTAL_SALES