-- 코드를 작성해주세요
select YEAR(A.DIFFERENTIATION_DATE) as YEAR,
        (B.SIZE-A.SIZE_OF_COLONY) as YEAR_DEV,
        ID
from ECOLI_DATA A,
    (select YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE
    from ECOLI_DATA
    group by YEAR) B
where YEAR(A.DIFFERENTIATION_DATE)=B.YEAR
order by YEAR, YEAR_DEV