-- 코드를 입력하세요
SELECT CATEGORY, sum(SALES) as TOTAL_SALES
from BOOK_SALES s join BOOK b on s.BOOK_ID=b.BOOK_ID
where YEAR(SALES_DATE)='2022' and MONTH(SALES_DATE)='01'
group by CATEGORY
order by CATEGORY